<script lang="ts">
	import OtpInput from '$lib/components/OtpInput.svelte';
	import { settingsStore } from '$lib/stores/settings.svelte';
	import Icon from '@iconify/svelte';

	let copied = $state(false);

	function handleCopy() {
		navigator.clipboard.writeText(settingsStore.secret);
		copied = true;
		setTimeout(() => (copied = false), 2000);
	}
</script>

<div class="p-6">
	<h3 class="font-medium text-gray-900 mb-4">Set up Authenticator App</h3>

	<div class="flex flex-col md:flex-row gap-8">
		<!-- QR Code Column -->
		<div class="flex-shrink-0 flex justify-center bg-white p-2 rounded-lg border border-gray-200">
			{#if settingsStore.qrCodeUrl}
				<img src={settingsStore.qrCodeUrl} alt="QR Code" class="w-40 h-40" />
			{:else}
				<div class="w-40 h-40 flex items-center justify-center bg-gray-100 rounded text-gray-400">
					<Icon icon="lucide:loader-2" class="animate-spin" width="24" />
				</div>
			{/if}
		</div>

		<!-- Logic Column -->
		<div class="flex-1 space-y-4">
			<ol class="list-decimal list-inside text-sm text-gray-600 space-y-2">
				<li>
					Install <strong>Google Authenticator</strong> or <strong>Authy</strong> on your phone.
				</li>
				<li>Scan the QR code or manually enter the key below.</li>
				<li>Enter the 6-digit code generated by the app.</li>
			</ol>

			<!-- Copy Secret -->
			<div class="flex items-center gap-2 bg-white border border-gray-200 rounded-md p-2 max-w-sm">
				<code class="flex-1 font-mono text-xs text-gray-800 tracking-wider">
					{settingsStore.secret}
				</code>
				<button
					onclick={handleCopy}
					class="text-gray-400 hover:text-gray-600 transition-colors"
					aria-label="Copy secret"
				>
					{#if copied}
						<Icon icon="lucide:check" class="text-green-600" />
					{:else}
						<Icon icon="lucide:copy" />
					{/if}
				</button>
			</div>

			<div class="pt-2">
				<span class="block text-sm font-medium text-gray-700 mb-2"> Verification Code </span>
				<OtpInput bind:value={settingsStore.verificationCode} disabled={settingsStore.loading} />
			</div>

			<!-- Buttons -->
			<div class="flex gap-3 pt-2">
				<button
					onclick={() => settingsStore.verifyAndEnable2FA()}
					disabled={settingsStore.loading || settingsStore.verificationCode.length !== 6}
					class="rounded-md bg-green-900 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-green-800 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
				>
					{settingsStore.loading ? 'Verifying...' : 'Verify & Activate'}
				</button>
				<button
					onclick={() => settingsStore.resetQRCodeSetup()}
					class="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50"
				>
					Cancel
				</button>
			</div>
		</div>
	</div>
</div>
